version: '3.8'

services:
  # --- Core Messaging System ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # Expose Kafka for your local Python scripts
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

  # --- Time-Series Database (Data Sink) ---
#  influxdb:
#    image: influxdb:2.7
#    container_name: influxdb
#    ports:
#      - "8086:8086" # Expose InfluxDB UI and API
#    volumes:
#      - influxdb-storage:/var/lib/influxdb2 # Persist data
#    environment:
#      # These variables set up the initial user, org, bucket, and token for InfluxDB v2
#      - DOCKER_INFLUXDB_INIT_MODE=setup
#      - DOCKER_INFLUXDB_INIT_USERNAME=admin
#      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
#      - DOCKER_INFLUXDB_INIT_ORG=my-org
#      - DOCKER_INFLUXDB_INIT_BUCKET=github-events
#      # This is the API token your Beam pipeline will use to write data
#      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token

  # --- Visualization Platform ---
#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    depends_on:
#      - influxdb
#    ports:
#      - "3000:3000" # Expose Grafana UI
#    volumes:
#      - grafana-storage:/var/lib/grafana # Persist dashboards
#      # This mounts the provisioning file to auto-configure the InfluxDB datasource
#      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
#    environment:
#      # This tells Grafana to use the InfluxDB token from the environment
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_DATASOURCES_INFLUXDB_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:-my-super-secret-auth-token}

# Define named volumes for data persistence
#volumes:
#  influxdb-storage:
#  grafana-storage: